# Generated by Django 4.2.28 on 2026-02-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tasks", "0002_task_user")]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        )
    ]
